export const testCars = [
    {
        id: 1,
        carName: 'BMW M3',
        model: 'M3 COMPETITION XDRIVE',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Manual',
        year: 2022,
        price: 230,
        engineDisplacement: 3000,
        enginePower: "395 kw (510 hp)",
        consumption: "7.4"
    },
    {
        id: 2,
        carName: 'Ford Mustang',
        model: '5,0GT V8',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2019,
        price: 120,
        engineDisplacement: 5038,
        enginePower: "331kw (450 hp)",
        consumption: "12"
    },
    {
        id: 3,
        carName: 'Toyota',
        model: 'RAV4',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2020,
        price: 120,
        engineDisplacement: 2500,
        enginePower: "203 hp",
        consumption: "6.3"
    },
    {
        id: 4,
        carName: 'Honda',
        model: 'Civic',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2018,
        price: 120,
        engineDisplacement: 1800,
        enginePower: "158 hp",
        consumption: "6.3"
    },
    {
        id: 5,
        carName: 'Honda',
        model: 'Accord',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2019,
        price: 150,
        engineDisplacement: 1500,
        enginePower: "192 hp",
        consumption: "6.3"
    },
    {
        id: 6,
        carName: 'Honda',
        model: 'CR-V',
        seats: 5,
        fuel: 'Diesel',
        transmission: 'Automatic',
        year: 2020,
        price: 180,
        engineDisplacement: 2000,
        enginePower: "190 hp",
        consumption: "7.4"
    },
    {
        id: 7,
        carName: 'Nissan',
        model: 'Sentra',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2018,
        price: 60,
        engineDisplacement: 1800,
        enginePower: "124 hp",
        consumption: "6.3"
    },
    {
        id: 8,
        carName: 'Nissan',
        model: 'Altima',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2019,
        price: 150,
        engineDisplacement: 2500,
        enginePower: "182 hp",
        consumption: "6.3"
    },
    {
        id: 9,
        carName: 'Nissan',
        model: 'Rogue',
        seats: 5,
        fuel: 'Hybrid',
        transmission: 'Automatic',
        year: 2020,
        price: 180,
        engineDisplacement: 2000,
        enginePower: "141 hp",
        consumption: "7.4"
    },
    {
        id: 10,
        carName: 'Ford',
        model: 'Fiesta',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2018,
        price: 120,
        engineDisplacement: 1600,
        enginePower: "120 hp",
        consumption: "6.3"
    },
    {
        id: 11,
        carName: 'Ford',
        model: 'Focus',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2019,
        price: 50,
        engineDisplacement: 2000,
        enginePower: "160 hp",
        consumption: "6.3"
    },
    {
        id: 12,
        carName: 'Ford',
        model: 'Escape',
        seats: 5,
        fuel: 'Electric',
        transmission: 'Automatic',
        year: 2020,
        price: 75,
        engineDisplacement: 2000,
        enginePower: "165 hp",
        consumption: "7.4"
    },
    {
        id: 13,
        carName: 'Citroën C4 Picasso',
        model: 'C4 Picasso',
        seats: 7,
        fuel: 'Diesel',
        transmission: 'Automatic',
        year: 2015,
        price: 65,
        engineDisplacement: 1997,
        enginePower: "150 hp",
        consumption: "6.3"
    },
    {
        id: 14,
        carName: 'Citroën C3',
        model: 'C3',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2018,
        price: 50,
        engineDisplacement: 1200,
        enginePower: "82 hp",
        consumption: "6.3"
    },
    {
        id: 15,
        carName: 'Citroën C3 Aircross',
        model: 'C3 Aircross',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2019,
        price: 60,
        engineDisplacement: 1200,
        enginePower: "110 hp",
        consumption: "6.3"
    },
    {
        id: 16,
        carName: 'Citroën C5 Aircross',
        model: 'C5 Aircross',
        seats: 5,
        fuel: 'Diesel',
        transmission: 'Automatic',
        year: 2020,
        price: 70,
        engineDisplacement: 1600,
        enginePower: "130 hp",
        consumption: "7.4"
    },
    {
        id: 17,
        carName: 'Citroën C4 Cactus',
        model: 'C4 Cactus',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2018,
        price: 55,
        engineDisplacement: 1200,
        enginePower: "110 hp",
        consumption: "6.3"
    },
    {
        id: 18,
        carName: 'Citroën C1',
        model: 'C1',
        seats: 4,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2019,
        price: 40,
        engineDisplacement: 1000,
        enginePower: "72 hp",
        consumption: "6.3"
    },
    {
        id: 19,
        carName: 'Citroën C3 Picasso',
        model: 'C3 Picasso',
        seats: 5,
        fuel: 'Diesel',
        transmission: 'Automatic',
        year: 2015,
        price: 45,
        engineDisplacement: 1600,
        enginePower: "90 hp",
        consumption: "6.3"
    },
    {
        id: 20,
        carName: 'Citroën C4',
        model: 'C4',
        seats: 5,
        fuel: 'Petrol',
        transmission: 'Automatic',
        year: 2018,
        price: 50,
        engineDisplacement: 1200,
        enginePower: "110 hp",
        consumption: "6.3"
    }
];
