export const testCars = [
    {
        id: 1,
        carName: 'BMW M3',
        model: 'M3 COMPETITION XDRIVE',
        seats: 5,
        fuel: 'Gasoline',
        transmission: 'Manual',
        year: 2022,
        price: 230,
        engineDisplacement: 3000,
        enginePower: "395 kw (510 hp)",
        consumption: "7.4"
    },
    {
        id: 2,
        carName: 'Toyota',
        model: 'Camry',
        seats: 5,
        fuel: 'Diesel',
        transmission: 'Manual',
        year: 2019,
        price: 90,
        engineDisplacement: 2500,
        enginePower: "202 hp",
        consumption: "5.5"
    },
    {
        id: 3,
        carName: 'Toyota',
        model: 'RAV4',
        seats: 5,
        fuel: 'Gasoline',
        transmission: 'Automatic',
        year: 2020,
        price: 120,
        engineDisplacement: 2500,
        enginePower: "203 hp",
        consumption: "6.3"
    },
    {
        id: 4,
        carName: 'Honda',
        model: 'Civic',
        seats: 5,
        fuel: 'Gasoline',
        transmission: 'Automatic',
        year: 2018,
        price: 120,
        engineDisplacement: 1800,
        enginePower: "158 hp",
        consumption: "6.3"
    },
    {
        id: 5,
        carName: 'Honda',
        model: 'Accord',
        seats: 5,
        fuel: 'Gasoline',
        transmission: 'Automatic',
        year: 2019,
        price: 150,
        engineDisplacement: 1500,
        enginePower: "192 hp",
        consumption: "6.3"
    },
    {
        id: 6,
        carName: 'Honda',
        model: 'CR-V',
        seats: 5,
        fuel: 'Gasoline',
        transmission: 'Automatic',
        year: 2020,
        price: 180,
        engineDisplacement: 2000,
        enginePower: "190 hp",
        consumption: "7.4"
    },
    {
        id: 7,
        carName: 'Nissan',
        model: 'Sentra',
        seats: 5,
        fuel: 'Gasoline',
        transmission: 'Automatic',
        year: 2018,
        price: 60,
        engineDisplacement: 1800,
        enginePower: "124 hp",
        consumption: "6.3"
    },
    {
        id: 8,
        carName: 'Nissan',
        model: 'Altima',
        seats: 5,
        fuel: 'Gasoline',
        transmission: 'Automatic',
        year: 2019,
        price: 150,
        engineDisplacement: 2500,
        enginePower: "182 hp",
        consumption: "6.3"
    },
    {
        id: 9,
        carName: 'Nissan',
        model: 'Rogue',
        seats: 5,
        fuel: 'Hybrid',
        transmission: 'Automatic',
        year: 2020,
        price: 180,
        engineDisplacement: 2000,
        enginePower: "141 hp",
        consumption: "7.4"
    },
    {
        id: 10,
        carName: 'Ford',
        model: 'Fiesta',
        seats: 5,
        fuel: 'Gasoline',
        transmission: 'Automatic',
        year: 2018,
        price: 120,
        engineDisplacement: 1600,
        enginePower: "120 hp",
        consumption: "6.3"
    },
    {
        id: 11,
        carName: 'Ford',
        model: 'Focus',
        seats: 5,
        fuel: 'Gasoline',
        transmission: 'Automatic',
        year: 2019,
        price: 50,
        engineDisplacement: 2000,
        enginePower: "160 hp",
        consumption: "6.3"
    },
    {
        id: 12,
        carName: 'Ford',
        model: 'Escape',
        seats: 5,
        fuel: 'Electric',
        transmission: 'Automatic',
        year: 2020,
        price: 75,
        engineDisplacement: 2000,
        enginePower: "165 hp",
        consumption: "7.4"
    }
];
